# Site
repository: gudwls215/gudwls215.github.io
# favicon: images/favicon.ico

# Personal info
name: 김형진
title: 풀스택 엔지니어
email: gudwls215@gmail.com
website: https://velog.io/@gudwls215

# Social links
# twitter_username: gudwls215
github_username:  gudwls215
# dribbble_username: jekyll
facebook_username: gudwls215
# flickr_username: jekyll
# linkedin_username: gudwls215
# pinterest_username: jekyll
youtube_username: UCSEOUzkGNCT_29EU_vnBYjg

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Java & Spring / NodeJS & TypeScript, AWS 기반의 10년차 서버 백엔드 개발자로
  **누적 회원수 100만**의 에듀테크, **MAU 1,500만 & 일 주문 300만 커머스**, **일 PV 2,000만 포탈** 등의 서비스에서 백엔드 플랫폼 개발 및 AWS 인프라 구축 등을 해왔습니다.<br/>
  개인이 하고 싶은 일 보다는 <mark>회사와 팀에 도움이 되는</mark> 개발을 해야한다는 생각에
  xtrabackup, pt-online-schema-change, MHA를 활용한 MySQL 운영, Ansible을 이용한 IDC 인프라 운영을 해오기도 했습니다.<br/>
  <mark>테스트 코드</mark> 작성을 당연하게 생각하여 전 직장 시스템의 경우 2500개의 테스트 케이스가 하루에도 수십번 수행되는 환경을 구성하였습니다.<br/>
  현재는 <mark>CTO</mark>로 사업과 제품의 방향성을 고려하여 채용, 시스템 설계, 팀 매니징, <mark>팀원과 팀의 성장</mark> 등을 주요 업무로 하고 있습니다.<br/>


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 협력 프로젝트에서 활동했습니다.
   - 비사이드의 아카이빙 서비스 백엔드 개발
   - f-thon 제 2회 해커톤 참여 및 인기상 수상
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
